ci: Test skip release job

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -40,7 +40,7 @@ jobs:
   #       path: dist/
 
   release:
-    name: Publish Python 🐍 distribution 📦 to TestPyPI
+    name: Release new 🐍 version and Publish 📦 to TestPyPI
     runs-on: ubuntu-latest
     concurrency: release
 
@@ -57,7 +57,7 @@ jobs:
       with:
         fetch-depth: 0
 
-    - name: Python Semantic Release
+    - name: Check for new Relase and ...release
       uses: python-semantic-release/python-semantic-release@master
       with:
         github_token: ${{ secrets.ACCESS_TOKEN }}
@@ -80,8 +80,17 @@ jobs:
     #   with:
     #     github_token: ${{ secrets.ACCESS_TOKEN }}
         # <other options here>
+    - name: Check if dist/ folder exists (Release check)
+      run: |
+        if [ ! -d "dist" ]; then
+          echo "dist/ folder does not exist, skipping the job."
+          exit 78 # Exit code 78 is used for skipping jobs in GitHub Actions
+        else
+          echo "dist/ folder exists, proceeding with the job."
+        fi
 
-    - name: Publish package distributions to TestPyPI
+    - name: Publish package to TestPyPI if new release available
+      if: always()
       uses: pypa/gh-action-pypi-publish@release/v1
       with:
         user: __token__
